### ISSUE TITLE
Using HTTPS

### ISSUE THREAD

**Issue by imeidopf** [therecluse26/PHP-Login#115]
How can I get this to send an https verify link? The email sends a regular http://www.example.com/ URL, but I want it to send https://www.example.com/ instead.

**Comment by brianjcollins** [comment]
It's not explicitly defined anywhere, it uses $base_url, so if you were on https:// it would send the verify as https:// otherwise, http:// will be used.  If you would like to force it to https://, I would do something like...

`$verifyurl = preg_replace("/^http:/i", "https:", $verifyurl);`

Insert it after line 14 in login/includes/mailsender.php

https://github.com/fethica/PHP-Login/blob/b6ef2542edaf72f85e04bb9b468bb01f9a33af09/login/includes/mailsender.php#L14

**Comment by kungknut** [comment]
You could also configure your webserver to redirect all connections to HTTPS. Then all links that's already sent would also be using HTTPS and your users will always use an encrypted connection.
