### ISSUE TITLE
Change to dbconn.php constructor class on dev branch

### ISSUE THREAD

**Issue by zackoch** [therecluse26/PHP-Login#125]
I couldn't figure out how to do a pull request.
I received the following error -
 PHP Fatal error:  Uncaught Error: Call to protected DbConn::__construct() from invalid context in /var/www/html/login/ajax/createuser.php:31\nStack $

I fixed it by changing line 98 `protected function __construct()` to ` public function __construct()`

It appears as though this was committed @Brad Magyar and changed recently. It used to be simply `function__construct()` - I am not sure the repercussions of making this public. Someone please review

**Comment by zackoch** [comment]
Any input?

**Comment by SammF10930** [comment]
Your change is fine, it's good habit to define visibility which is why someone will have opted to update to protected, however public will also work. Here are the difference between visibility types:

- _public_:  your variable/function will be available from anywhere, other classes and instances of the object.

- _private_:  your variable/function will be visible in its own class only.

- _protected_:  your variable/function will be visible in all classes that extend current class including the parent class.

For more information you can read up on the difference here:
http://php.net/manual/en/language.oop5.visibility.php

**Comment by zackoch** [comment]
@SammF10930 - I guess my follow-up question would be why would I receive that error if it was possible to be protected? The maintainer of this project needs to move it somewhere else for it to be available elsewhere in the code, no?

**Comment by zackoch** [comment]
Okay - getting more into object oriented php as opposed to my experience in linear.

So what's happening here has to do with class inheritance I think.

class NewUser extends dbconn, but dbconn's function __constuct() is protected.

@SammF10930 you're saying that protected functions will be visible in all classes that extend the current class (dbconn is current, NewUser extends dbconn)  therefore why is that error happening?

Per @fethica code, he/she is taking an extension of class dbconn as NewUser and trying to use it's var's properly. I'm not quite sure what php is complaining about then.

**Comment by zackoch** [comment]
I haven't tried it - but is there a way to pull the createUser function out of NewUser by using a getter? $a->createUser(); instead of instantiating NewUser? Maybe I'm onto the wrong idea here.

**Comment by therecluse26** [comment]
@zackoch I don't know how I missed this from so long ago, sorry about that. I'm the primary developer on this project and it's hard to keep up with all of the issues in my spare time. I ended up changing visibility of the constructor to `public` because I was running into inheritance issues also. My general rule of thumb is to lock things down to `private` or `protected` unless I absolutely need them to be public.

Since you asked this, I've made a lot of changes to the code base in general and consolidated the class files to be a bit more sane and logical, so the `NewUser` class has been merged into `UserHandler` and the `createUser()` method is static, so you don't actually need to instantiate anything to use it. You can just call it like so: `UserHandler::createUser(array $userarray);`

You can investigate the code of `createUser` to see what data actually needs to be inside of the user array parameter. Hope that helps!
