### ISSUE TITLE
Error 404 - Object not found!

### ISSUE THREAD

**Issue by Baxthar** [therecluse26/PHP-Login#140]
I created a user inside the database, log in with it and I keep getting to the checklogin.php page and it keeps giving me this error: 

Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.
If you think this is a server error, please contact the webmaster.
Error 404
localhost
Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11

It works sometimes but then most of the time it doesn't.

**Comment by Baxthar** [comment]
Typed in the correct username and password, even an incorrect username and password yet both take my to checklogin.php and it stays there.

**Comment by therecluse26** [comment]
Hi @Baxthar  could you tell me what the URL is showing in your address bar when you get that error?

**Comment by R1NTS1** [comment]
I have same 404 Error.
URL is http://mydomain.fi/install/login/index.php?

**Comment by therecluse26** [comment]
@R1NTS1 @Baxthar , which version are you using? 2 or 3?

**Comment by R1NTS1** [comment]
@therecluse26
I use version 3.

**Comment by spamgunn** [comment]
I was getting this error too. Mine was also not able to find the css library, etc, when I would manually navigate to the login page. I think it was because I had used the automated install, with the default (prepopulated) value of the root install path plus "/install" for the Base URL as the base url. Does that sound right?
