### ISSUE TITLE
Checklogin

### ISSUE THREAD

**Issue by Baxthar** [therecluse26/PHP-Login#141]
I deleted the original index.php because I didn't need it and changed it to the main_login.php as I want that as the first page people go to but when I log in with the correct username and password I keep getting taken to the checklogin.php page with the output: {"username":"admin","response":"true"}, I then go back to localhost and it takes me to the page I want it to.

**Comment by tomcatbuzz** [comment]
Why did you delete it? If it is not supposed to be part of the module the package owners would have removed it. You should check all of the files to see how they function between each other. All new pages (and existing ones) need to include the Loginheader.php. They will all redirect for a login. Mainlogin.php  redirects to the index.php after the sign in SESSION has been verified. The reason you are having problems is because you just started deleting files. Try using the module like it is intended. Focus your look at the Index.php that is the landing page after you login. The index.php also Displays the message letting users know they have been logged in and contains the Logout function. I would recommend making a back-up copy of the index.php then create your Own home page--> using the index.php and build around that. That is how you will get your users to see the page you want.    On Saturday, November 11, 2017, 8:02:53 PM EST, Baxthar <notifications@github.com> wrote:  
 
 
I deleted the original index.php because I didn't need it and changed it to the main_login.php as I want that as the first page people go to but when I log in with the correct username and password I keep getting taken to the checklogin.php page with the output: {"username":"admin","response":"true"}, I then go back to localhost and it takes me to the page I want it to.
