### ISSUE TITLE
Disable Validate username

### ISSUE THREAD

**Issue by cdmarioe** [therecluse26/PHP-Login#143]
Where can i disable the validation just for username?

**Comment by cdmarioe** [comment]
No way?

**Comment by therecluse26** [comment]
Hey @cdmarioe , could you describe a bit more what you're trying to accomplish and why you'd want to disable username validation? I'm not sure it's possible just because of how login systems are designed to work, the username acts as a database lookup, so if there were no username, there'd be no way to return the proper user.

**Comment by shaunrc493** [comment]
I don't want to tread on your feet @therecluse26 but in includes/newuserform.php you can change the prepared statement to
`$stmt = $db->conn->prepare("INSERT INTO ".$tbl_members." (id, username, password, email, verified)
            VALUES (:id, :username, :password, :email, 1)");`

This will automatically validate the user when creating an account and you can then disable them manually via the database.

Sorry if that's not what you're looking for though!

**Comment by therecluse26** [comment]
Ah, did you mean you want to bypass user verification @cdmarioe ? If that's the case then what @shaunrc493 suggested should do it for you :) Just be aware that this can open up a big security hole allowing bots and so forth to potentially sign themselves up to your site.
