### ISSUE TITLE
Email Validation 

### ISSUE THREAD

**Issue by lipinnambiar** [therecluse26/PHP-Login#144]
I am unable to validate with email, because email not receiving

**Comment by cdmarioe** [comment]
You've configured the config.php file? 
////ONLY set this if you want a moderator to verify users and not the users themselves, otherwise leave blank or comment out
$admin_email = 'example@gmail.com';
//Set this for global site use
$site_name = 'Test Site';
//Maximum Login Attempts
$max_attempts = 5;
//Timeout (in seconds) after max attempts are reached
$login_timeout = 300;
//ONLY set this if you want a moderator to verify users and not the users themselves, otherwise leave blank or comment out
$admin_email = 'YourAdminEmail@gmail.com';
//EMAIL SETTINGS
//SEND TEST EMAILS THROUGH FORM TO https://www.mail-tester.com GENERATED ADDRESS FOR SPAM SCORE
$from_email = 'example2@gmail.com'; //Webmaster email
$from_name = 'Test Email or Subject'; //"From name" displayed on email
//Find specific server settings at https://www.arclab.com/en/kb/email/list-of-smtp-and-pop3-servers-mailserver-list.html
$mailServerType = 'smtp';
//IF $mailServerType = 'smtp'
$smtp_server = 'smtp.gmail.com';
$smtp_user = 'example2@gmail.com';
$smtp_pw = 'yourEmailPassword';
$smtp_port = 465; //465 for ssl, 587 for tls, 25 for other
$smtp_security = 'ssl';//ssl, tls or ''

??????

**Comment by lipinnambiar** [comment]
Yes below error foud

Warning: require(scripts/PHPMailer/PHPMailerAutoload.php): failed to open stream: No such file or directory in /home/content/60/12267960/html/login/login/includes/mailsender.php on line 6

Fatal error: require(): Failed opening required 'scripts/PHPMailer/PHPMailerAutoload.php' (include_path='.:/usr/local/php5_6/lib/php') in /home/content/60/12267960/html/login/login/includes/mailsender.php on line 6

**Comment by tomcatbuzz** [comment]
It sounds like you are missing the PHP Mailer package in your Scripts fill in the package tree. I think originally there was no file there, but now the PHP Mailer package is there. Check the Scripts folder to see if you have the PHP Mailer included. I have attached a link directly for the scripts contents.   https://github.com/fethica/PHP-Login/tree/master/login/scripts
    On Tuesday, November 21, 2017, 9:27:02 AM EST, lipinnambiar <notifications@github.com> wrote:  
 
 
Yes below error foud

Warning: require(scripts/PHPMailer/PHPMailerAutoload.php): failed to open stream: No such file or directory in /home/content/60/12267960/html/login/login/includes/mailsender.php on line 6

Fatal error: require(): Failed opening required 'scripts/PHPMailer/PHPMailerAutoload.php' (include_path='.:/usr/local/php5_6/lib/php') in /home/content/60/12267960/html/login/login/includes/mailsender.php on line 6

**Comment by therecluse26** [comment]
Hey @lipinnambiar , I pushed a major update yesterday with a ton of new features including an installer that should hopefully take the headache out of some of these dependency issues. Please clone it and give it a shot. I'm going to close this issue for now (just trying to clear out the inbox a bit), but feel free to re-open it if you still have problems. Thanks!
