### ISSUE TITLE
Multi User Levels

### ISSUE THREAD

**Issue by Bigben83** [therecluse26/PHP-Login#169]
I cant see much in the way of Multi user levels.
i.e.
viewer
user
super-user
admin
super-admin

Or am i not looking in the right place. the instructions for use could be a bit more detailed. :-)

works well, having to be a root user for mysql is a bit of a hassle on a cloud based VPS

**Comment by therecluse26** [comment]
You don't have to be an actual root-user, you just need to have high enough
permissions to do things like create/delete triggers, events, etc, as well
as create schemas and tables, so that's why I just recommend having root
privileges.

And no, I didn't really add very granular user levels, just admins, a
super-admin and standard users. If you want more a more granular role
setup, that's something you'd have to roll on your own setup for that. The
problem with me pre-defining a bunch of roles is that it makes it a lot
more opinionated and forces you to use it a certain way, which kind of goes
against the idea of why I wanted to build this, it's more meant to be a
jumping-off point than anything. Unfortunately, with an auth system, it's
pretty difficult to build it without any opinionated-ness at all, but I
wanted to keep it to a minimum.

I do have plans though to alter the role setup a bit in a future release to
make it more easily extensible through the database rather than through
hardcoding, so keep your eyes open for that. In retrospect I do realize
that I should have built it that way in the first place.
