### ISSUE TITLE
Update prosess

### ISSUE THREAD

**Issue by hbrekke** [therecluse26/PHP-Login#189]
Is there a updateprosess, where it just will update core, or do I need to 'reinstall' the whole 'system'?

**Comment by therecluse26** [comment]
Working on that right now actually. As of now, there's no "update" process per-se, since the database has largely remained consistent, but with my next release there will be a few major changes to the structure of the DB, so I'm creating a migration tool to assist with that. Typically though, with code updates, you won't need to do anything like that, it'll generally just be an issue of doing a `git pull`
