### ISSUE TITLE
i got this error after installation on local pc(XAMPP)

### ISSUE THREAD

**Issue by meetmec12** [therecluse26/PHP-Login#225]
Warning: require(C:\xampp\htdocs\scl/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\scl\login\misc\pagehead.php on line 8

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\scl/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\scl\login\misc\pagehead.php on line 8

**Comment by devept** [comment]
Warning: require(C:\wamp64\www\d/vendor/autoload.php):

**Comment by diggidan** [comment]
Same here!

**Comment by rwegera** [comment]
To be able to setup this on Xampp you need to do the followings:

1. Install Windows composer from [official website](https://getcomposer.org/download/)
2. Get inside your **PHP-Login folder** (in xampp) in your CMD and run `composer install --no-dev` 
if the above command fails due to CURL and SSL certificates errors, fix the issue with this.
Do XAMPP - CURL SSL Setup from [here](https://odan.github.io/2017/03/30/xampp-curl-ssl-setup.html)
 After completing what instructed in the above link also change 
`openssl.cafile="C:\xampp\apache\bin\curl-ca-bundle.crt"` 
to
`openssl.cafile="C:\xampp\php\extras\ssl\cacert.pem"`

3. Stop/Start Apache 
4 . Get inside your **PHP-Login folder** (in xampp) in your CMD and `composer install --no-dev` should run successfully.
5. Now you are ready to go to `http://localhost:[port]/[path-to-PHP-login]/install`
HOPE THIS HELP YOU ALL

**Comment by mattish91** [comment]
> 
> 
> **### To be able to setup this on Xampp you need to do the followings:**
> 
>     1. Install **Composer** on Windows  from [official website](https://getcomposer.org/download/)
> 
>     2. Get inside your **PHP-Login folder** (in xampp) in your CMD and run `composer install --no-dev`
>        if the above command fails due to CURL and SSL certificates errors, fix the issue with this.
>        Do XAMPP - CURL SSL Setup from [here](https://odan.github.io/2017/03/30/xampp-curl-ssl-setup.html)
>        After completing what instructed in the above link also change
>        `openssl.cafile="C:\xampp\apache\bin\curl-ca-bundle.crt"`
>        to
>        `openssl.cafile="C:\xampp\php\extras\ssl\cacert.pem"`
> 
>     3. Stop/Start Apache
> 
>     4. Get inside your **PHP-Login folder** (in xampp) in your CMD and `composer install --no-dev` should run successfully.
> 
>     5. Now you are ready to go to `http://localhost:[port]/[path-to-PHP-login]/install`
>        HOPE THIS HELP YOU ALL

it would be much easier if they installed a officially supported pre-compiled PHP package from here and just enable it in php.ini for their project (i have done this as my current setup) it does work fine with PHP 7.3.3 as well. (in this package you will get almost all php modules currently availiable).
