### ISSUE TITLE
Dev branch - VERY long page loads, no errors thrown

### ISSUE THREAD

**Issue by joebeaver89** [therecluse26/PHP-Login#73]
I installed using the web based installer - all fine.
I logged in and added phpmailer config, since that each page load takes a really long time (like 3 full minutes), I still get the xER41300 mail error and email_working in the database says false.

The PHPmailer config is all correct - I manually set the email_working field in the database to true and everything works quickly, emails send file for new users and things get entered into the mail log successfully.

**Comment by joebeaver89** [comment]
PS. I realise this is the dev branch and not everything will work as it should - just thought I should report in case it wasn't known about. Let me know if you don't want dev branch issues logged (because I found another)

**Comment by rzrbit** [comment]
I'm having this same issue.  I am not using curl and wonder if that's part of the issue.  Were you able to make any progress with this one?

**Comment by therecluse26** [comment]
Currently how I have it set up is to require you to fill in your SMTP
settings in the config section, save the settings and then hit the test
connection button. That should automatically switch the "email_working"
setting to true in the database and get rid of the error. This is basically
because of how crucial email is for the login system to work properly, if
connection fails, it continually tries to connect and spits out that error
so that the admin is quickly made aware and can rectify the problem. If
email is down, most of the important functionality of the plugin breaks.

But thank you for reporting this! I absolutely would appreciate any other
bugs you've uncovered. I'll try to get to them as soon as I can, I've still
been busy, unfortunately. The installer is the one part that is
consistently buggy as of now and is what's preventing me from being able to
push this to the master branch. Cross/platform compatibility is tricky for
an installer like this, so I also am building out a manual installer
process that throws out all of the sql scripts for you, so that should help
me get everything pushed out sooner. That, and documentation is my least
favorite thing on earth, so it takes me forever :P

**Comment by rzrbit** [comment]
Thanks for the quick reply!  I think I narrowed down my issue to not having composer setup when I ran the installer.  The installer appeared to work the first time but it just kind of stopped when it hit 100% but things kind of worked.  I had a bunch of errors related to the /vendor dir not existing (and none of the bootstrap/css was there) so I had been populating it manually as I discovered dependencies.  

Long story short, the issue is resolved.  I installed composer on my system (using this guide http://codezag.com/how-to-install-composer-wamp/) and re-ran the installer which ran much more gracefully and fully populated my /vendor dir with all the things I need (including composer which is interesting).  I reconfigured the mail settings with the fresh install and the email test is working.  I did a password reset test and an account creation from scratch test to make sure and the email comes through fine.  All is well.

**Comment by therecluse26** [comment]
Yeah, that's one of the issues I'm trying to resolve. For this type of
installation (since it relies on composer), it's tricky to get it working
cross-platform because of how varied systems can be, so I've been focused
on trying to get it to be semi-portable, which will probably include
bundling some binaries into the install directory. Anyways, glad you got it
working, keep a look out for future updates!
