### ISSUE TITLE
Add a new field on signup form

### ISSUE THREAD

**Issue by kstefanou52** [therecluse26/PHP-Login#80]
Hello,

I want to add a new field on the signup form called fullname. I add the column fullname on the member table in my database. I add the necessary variables on this files: signup.php, create user.php & newuserform.php .
All seems to be fine but when I try to complete the signup form I get this error "Username or email already exists" but this is not true so I checked this error and it translates to this "SQLSTATE[23000]".

In addition all the others things before I change these files worked like a charm.
Thank you in advance for your help and your time,
Kostis

**Comment by VA7NFH** [comment]
That error is coming because you also need to add the fullname column to the members table of the database, after that it should work fine.

**Comment by dClark1967** [comment]
kstefanou52, I am not adding in any fields, however I was having the same issue and I tracked it down to being a problem with having $admin_email set (well in my case anyhow).

The issue comes to head in createuser.php (refer lines below) 

`if (isset($admin_email)) {
	$newemail = $admin_email;
} else {
	$newemail = $_POST['email'];
}`

It is sending the admin_email value to the new user form if you have the $admin_email set in the config.php file instead of the posted email address.

To fix this I made the following changes:

`} elseif (!filter_var($newemail, FILTER_VALIDATE_EMAIL) == true) {`
Changed to 
`} elseif (!filter_var($_POST['email'], FILTER_VALIDATE_EMAIL) == true) {`

`$response = $a->createUser($newuser, $newid, $newemail, $newpw);`
Changed to
`$response = $a->createUser($newuser, $newid, $_POST['email'], $newpw);`

I have not added any validation in for checking the $admin_email so assume it is entered correctly in the config.php file.

My suggestion to you is, if you have an $admin_email value set in config.php file, clear it out and see if your form posts with the new fields. If it does, then it isn't your new fields but the code listed above.

... and like always, I stand to be corrected if need be. :)
