### ISSUE TITLE
I am able to fork this project

### ISSUE THREAD

**Issue by kirkisanon** [therecluse26/PHP-Login#93]
Can i fork this project and do some work on project in work?

**Comment by therecluse26** [comment]
You can, however I have a fork of my own that has quite a bit of work added to it in the dev branch. Once I finish up some final things on the installation, I plan on merging it back into the master here. I can help you out with the installation process if you'd like because it may be a bit broken

https://github.com/therecluse26/PHP-Login/tree/dev

**Comment by kirkisanon** [comment]
in the dev PHP-Login i have an issues says i can't connect to database contact the system admin and relay this error - xER41300 followed your steps what did i do wrong?

**Comment by therecluse26** [comment]
Sure, that's a generic error that is set to pop up when the admin's smtp
email settings aren't set up properly. Go to the admin config panel, set up
your email settings, save and test them out and that should go away. I
didn't want to expose the fact that the overall email account wasn't set up
properly to end users, but it's a critical enough issue that the admin
should be alerted and fix it as soon as possible, because otherwise the
login system will not be able to either create new users or reset passwords.

**Comment by RealCrime** [comment]
Hey therecluse26, i need some help do you have a place i can contact you directly?

**Comment by therecluse26** [comment]
Sure, shoot me an email at braddmagyar@gmail.com. We can work through
getting you hooked up.

**Comment by RealCrime** [comment]
@therecluse26 sent you an email bud!
